---
name: Check docker syntax

"on":
  push:
    paths:
      - Containerfile*
      - .github/workflows/check-docker-syntax.yml
  pull_request:
    paths:
      - Containerfile*
      - .github/workflows/check-docker-syntax.yml

jobs:
  check-docker-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Containerfile
